splunk/eventgen

- build.xml
- lib/eventgenqueue.py
- lib/plugins/output/httpevent.py
> Revert "Bugfix/tools 451"

- splunk_eventgen/lib/eventgentimer.py
If the sample generation is not setup properly, we will have a rator spit out -1 as a count. In this case, no need to put that into a generation queue.
> Added a count check for data generation

- splunk_eventgen/lib/plugins/output/splunkstream.py
Changing a default queue to deque
> Converted a queue in splunkstream to deque

- docs/BASICS.md
- docs/CONFIGURE.md
- docs/REFERENCE.md
- splunk_eventgen/lib/eventgenconfig.py
- splunk_eventgen/lib/eventgentoken.py
1 add a replacement type 'seqfile' which performs like file and mvfile
2 use tokenfilecounter to iterator values from a specific file(column)
> requirements for sequentially replacement from a file

- docs/REFERENCE.md
- splunk_eventgen/default/eventgen.conf
- splunk_eventgen/lib/eventgenconfig.py
- splunk_eventgen/lib/eventgentimer.py
- splunk_eventgen/lib/plugins/rater/config.py
- tests/medium/plugins/test_file_output.py
- tests/medium/plugins/test_syslog_output.py
- tests/medium/plugins/test_tcp_output.py
- tests/medium/plugins/test_udp_output.py
count=-1 by default now, which should include/use all events from a sample. Count=0 now represents 0 events from the sample.
Also cleaned up some logging statements.
> Changing default count and count parsing

- splunk_eventgen/lib/plugins/output/splunkstream.py
> Fix bug #179 urlparams is not set

- docs/REFERENCE.md
- splunk_eventgen/default/eventgen.conf
Verbose keyword complains as the working keyword is verbosity.
no -v will only output error
-v will output info
-vv will otuput debug
> Changed verbose -> verbosity

- .gitignore
- tests/perf/eventgen.conf.test1
- tests/perf/eventgen.conf.test2
- tests/perf/eventgen.conf.test3
- tests/sample_eventgen_conf/autotimestamp/eventgen.conf.autotimestamp
- tests/sample_eventgen_conf/backfill/eventgen.conf.backfillend
- tests/sample_eventgen_conf/backfill/eventgen.conf.backfillreplay
- tests/sample_eventgen_conf/backfill/eventgen.conf.backfillsample
- tests/sample_eventgen_conf/breakersample/eventgen.conf.breakersample
- tests/sample_eventgen_conf/breakersample/eventgen.conf.randombreakersample
- tests/sample_eventgen_conf/bundlelines/eventgen.conf.bundlelinescsv
- tests/sample_eventgen_conf/bundlelines/eventgen.conf.bundlelinesraw
- tests/sample_eventgen_conf/largerconfig/eventgen.conf.largerconfig
- tests/sample_eventgen_conf/perdayvolume/eventgen.conf.perdayvolume
- tests/sample_eventgen_conf/perdayvolume/eventgen.conf.perdayvolumesinglerun
- tests/sample_eventgen_conf/perf/eventgen.conf.perfsample
- tests/sample_eventgen_conf/perf/eventgen.conf.perfsampleweblog
- tests/sample_eventgen_conf/perf/eventgen.conf.perfsampleweblog-s2s
- tests/sample_eventgen_conf/replay/eventgen.conf.badtimestamp
- tests/sample_eventgen_conf/replay/eventgen.conf.replay
- tests/sample_eventgen_conf/replay/eventgen.conf.timeorder
- tests/sample_eventgen_conf/replaytimestamp/eventgen.conf.replaytimestamp
- tests/sample_eventgen_conf/sample/eventgen.conf.epochtime
- tests/sample_eventgen_conf/sample/eventgen.conf.fullsample
- tests/sample_eventgen_conf/sample/eventgen.conf.longsample
- tests/sample_eventgen_conf/sample/eventgen.conf.randomsample
- tests/sample_eventgen_conf/sample/eventgen.conf.shortsample
- tests/sample_eventgen_conf/unit/eventgen.conf.config
this PR only fixes the sample file not found errors in test. 
In my local env, these cases have some other failures. 
Will fix these errors when we enable circle CI.
> change the sampleDir setting in test cases

- docs/REFERENCE.md
- splunk_eventgen/eventgen_core.py
- splunk_eventgen/lib/plugins/output/httpevent_core.py
- splunk_eventgen/lib/plugins/output/metric_httpevent.py
Put metrics output plugin code to develop
> fix metrics output mode

- splunk_eventgen/eventgen_core.py
- tests/large/conf/eventgen_sample_multiprocess.conf
- tests/large/conftest.py
- tests/large/test_mode_replay.py
- tests/large/test_mode_sample_multiprocess.py
- tests/large/utils/eventgen_test_helper.py
@lephino I removed the `self.workerQueue.unfinished_tasks > 0` and add corresponding test case for this. All functional tests passed. This might not be the final solution as we discussed in the issue. Will change based on your comments.
> Fix bug 230 and add test case

- docs/BASICS.md
- splunk_eventgen/__main__.py
* Fix example formatting in BASICS.md
* See http://splunk.github.io/eventgen/BASICS.html
* Make the --role CLI helper text consistent
> Minor doc fixes

- Makefile
- tests/large/conf/eventgen_plugin_splunkstream.conf
- tests/large/conf/eventgen_plugin_spool.conf
- tests/large/conftest.py
- tests/large/test_output_plugin.py
- tests/large/utils/eventgen_test_helper.py
Add functional tests for output plugin splunkstream and spool.
> add ft for splunkstream and spool

- splunk_eventgen/lib/requirements.txt
> Fix structlog dependency for app (#280)

- splunk_eventgen/lib/eventgentoken.py
- splunk_eventgen/lib/plugins/generator/perdayvolumegenerator.py
Replace with `random.SystemRandom`.
> Fix bug 286 random token replacement

- requirements.txt
Update Redis version to allow use of new functions such as `check_health`
> Update Redis Version

- splunk_eventgen/eventgen_api_server/eventgen_server_api.py
- splunk_eventgen/eventgen_core.py
- splunk_eventgen/lib/eventgentimer.py
Since previous change does not totally fix the oom issue and introduced potential other issues, revert it now.
> Revert oom fix change

- LICENSE
- requirements.txt
- splunk_eventgen/__main__.py
- splunk_eventgen/eventgen_api_server/eventgen_core_object.py
- splunk_eventgen/eventgen_core.py
- splunk_eventgen/lib/logging_config/__init__.py
- splunk_eventgen/lib/requirements.txt
- splunk_eventgen/splunk_app/bin/modinput_eventgen.py
Add `--disable-logging` option to disable the logging to address the oom issue.
I also removed `structlog` which does not have interface to change handler.
> Add disable logging option to fix oom

- docs/CHANGELOG.md
- release_tool/README.md
- release_tool/prepare_release_branch.py
> add release automation script

- splunk_eventgen/README/eventgen.conf.tutorial1
Timestamps were not getting replaced correctly in replay mode: #348
> fix tutorial token type

- docs/CHANGELOG.md
- pyproject.toml
- splunk_eventgen/splunk_app/default/app.conf
bump version with release script
> Release 7.1.1

- docs/CHANGELOG.md
- splunk_eventgen/splunk_app/default/app.conf
> Release eventgen 7.2.0. Merge to develop branch.
