splunk/eventgen

- splunk_eventgen/lib/eventgensamples.py
- splunk_eventgen/lib/plugins/generator/jinja.py
- splunk_eventgen/lib/plugins/generator/weblog.py
- tests/sample_eventgen_conf/perf/eventgen.conf.perfsample
- tests/sample_eventgen_conf/perf/eventgen.conf.perfsampleweblog
- tests/sample_eventgen_conf/perf/eventgen.conf.perfsampleweblog-s2s
- tests/sample_eventgen_conf/perf/eventgen.conf.perfweblog
- tests/sample_eventgen_conf/perf/eventgen.conf.perfwindbag
- Events generated by .csv sample files will use the index value from either the local or default .conf files
- Jinja generator now grabs and uses the local index value, if defined
- Weblog generator now grabs and uses the local index, source, sourcetype, and host, if defined
- Cleaned up some test samples and syntax warnings
> fix for csv index override + jinja/weblog generators

- splunk_eventgen/lib/eventgenconfig.py
- splunk_eventgen/lib/eventgensamples.py
- splunk_eventgen/lib/eventgentimer.py
- splunk_eventgen/lib/plugins/generator/replay.py
We are now supporting future events for the replay module. Splunk handles indexing future events so you can pre-generate all your future events and Splunk will index it at the future time as real data would come in.
> Added a future event generation for replay generator

- docs/PERFORMANCE.md
- docs/REFERENCE.md
- splunk_eventgen/README/eventgen.conf.spec
- splunk_eventgen/eventgen_core.py
- splunk_eventgen/lib/eventgenconfig.py
- splunk_eventgen/splunk_app/README/inputs.conf.spec
- splunk_eventgen/splunk_app/bin/modinput_eventgen.py
- splunk_eventgen/splunk_app/default/inputs.conf
- splunk_eventgen/splunk_app/lib/modinput/__init__.py
- Cleaned and updated performance docs
- Made default logging levels less verbose
- Modinput verbosity is no longer binary and accepts input from the app interface
> Clean performance docs and fix logging verbosity

- splunk_eventgen/lib/eventgenconfig.py
- splunk_eventgen/splunk_app/lib/modinput/fields.py
- Support for Splunk SPL Examples app: modinput can now parse and index events without hitting a ValueError
- Added safety check for allowed range of "verbosity" param and made its exception message more informative
> Modinput bugfix

- splunk_eventgen/lib/eventgenconfig.py
1. Change the log level of "Token at index %s invalid" message  to "error".
> Change token invalid log level to error

- splunk_eventgen/lib/plugins/output/modinput.py
- splunk_eventgen/splunk_app/lib/modinput/fields.py
Fixed a mistake I made where modinput would not allow users to change the logging verbosity and changed the output statement style to prevent broken pipes.
> Fix safety check and broken pipe

- splunk_eventgen/lib/eventgentimer.py
**What I did:**
Reduce the cpu time cost in timer.
**How I did:**
Use partial deep copy instead of deep copy when timer build a generator task.
**Detail:**
We run our profiling job for 100 seconds with the following results:
``` 
Clock type: CPU
Ordered by: totaltime, desc
name ncall tsub ttot tavg 
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py:145 deepcopy 1939865/191 24.41281 74.27245 0.000038
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py:306 _reconstruct 89025/191 3.045957 74.24512 0.000834
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py:253 _deepcopy_dict 89107/191 5.585420 74.17139 0.000832
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py:226 _deepcopy_list …
```
> use copy instead of deepcopy

- Makefile
fixes #128 
No update on `Splunk_eventgen/version.json` as this change only changes the build tooling and doesn't affect the functionality of eventgen.
> changed wget to curl

- splunk_eventgen/lib/outputplugin.py
- splunk_eventgen/lib/plugins/output/splunkstream.py
Fixing some messy logic in the splunkstream outputter. The logic separates events by unique source/sourcetype combos and sends a single http event to splunk for each group. We now dynamically append events to the sub-queues.
Addresses issue: #132
> Remove splunkstream queue separation

- docs/REFERENCE.md
- splunk_eventgen/lib/eventgensamples.py
- splunk_eventgen/lib/eventgentimer.py
Created timer.interval object that is adjusted by timeMultiple. The option can also work with sample mode now.
> Feature timeMultiple

- docs/CONFIGURE.md
- docs/REFERENCE.md
- docs/SETUP.md
- docs/TUTORIAL.md
- splunk_eventgen/README/eventgen.conf.spec
- splunk_eventgen/lib/plugins/generator/jinja.py
- splunk_eventgen/splunk_app/README/eventgen.conf.spec
- tests/medium/plugins/test_jinja_generator.py
- tests/sample_eventgen_conf/jinja/eventgen.conf.jinja_basic
- tests/sample_eventgen_conf/jinja/templates/test_jinja_basic.template
1. Fix error "AttributeError: 'NoneType' object has no attribute 'rfind'" when using jinja template under SA-Eventgen app.
2. Fix conf checking error  when starting Splunk for the jinja template settings.
3. Add document to address the permission issue: https://github.com/splunk/eventgen/issues/77
4. Fix a few typos.
> Fix jinja template bug under SA-Eventgen app

- docs/REFERENCE.md
- splunk_eventgen/lib/eventgentimer.py
- splunk_eventgen/lib/plugins/generator/windbag.py
- splunk_eventgen/lib/plugins/rater/config.py
- tests/perf/eventgen.conf.test1
- tests/sample_eventgen_conf/replay/eventgen.conf.replay
Patching up some edge cases that I discovered. End = 0 was generating a single interval of events, but it shouldn't generate any now. There is still no default for end, which is what causes it to run indefinitely.
There was also an issue with the windbag generator and count = -1. Since the generator does not use a sample directly, there is no telling what count should actually represent. We will now load the 'windbag' sample if we're using the generator and haven't found any sample yet. This allows count = -1 to continue to rely on the sample size. If users want a specific number of windbag events per interval, count will still work perfectly fine.
> Windbag generator/count + end=0 edge cases

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- CONTRIBUTING.md
- README.md
- docs/.gitignore
- docs/CONTRIBUTE.md
- docs/CONTRIBUTE_CODE.md
- docs/FILE_ISSUES.md
- docs/SUMMARY.md
- docs/index.md
update the contribute.md
Put a page about code contribution in docs.
> [Docs] update contribute docs

- docs/REFERENCE.md
- splunk_eventgen/lib/eventgenconfig.py
- splunk_eventgen/lib/eventgensamples.py
- splunk_eventgen/lib/generatorplugin.py
- splunk_eventgen/lib/outputcounter.py
This PR is to add an "extendIndexes" setting. We want to use this feature to set more indexes for one kind of event.
Here are things I have done:
1. Add  "extendIndexes" setting for each sample and it will be parsed in eventgensamples.py and then add a "index_list" for sample.
2. Generator will choose a index from index_list randomly if you set value to "extendIndexes".
> add extendIndexes feature

- splunk_eventgen/eventgen_nameko_server.py
When setup eventgen with 200+ indexers, any exceptions will terminate setup, thus default configure file is not re-written with indexers information.
> fix an issue that rest exceptions are not properly handled in setup API

- splunk_eventgen/eventgen_core.py
- splunk_eventgen/lib/eventgenoutput.py
- splunk_eventgen/lib/plugins/generator/default.py
It is ok to go over the interval time when end == 1 because the generation is not bound by the interval.
Also moving execution "tmp = [len(s['_raw']) for s in q]" inside of the conditional so remove unnecessary execution when it isn't Splunk Embedded mode.
> Clean up and interval error

- splunk_eventgen/lib/eventgensamples.py
This PR is to fix issue  https://github.com/splunk/eventgen/issues/259
> only load extendIndexes once

- Makefile
- splunk_eventgen/lib/eventgensamples.py
- splunk_eventgen/lib/generatorplugin.py
- tests/large/conf/eventgen_extend_index.conf
- tests/large/sample/cisco
- tests/large/test_extend_index.py
When I debug on this bug, I saw the variable `index_list` in eventgesamples.py was shared by each sample, which is not make sense(each sample should keep a new one). 
Then I just put the parse result into the "extendIndexes" and it fixed that bug. https://github.com/splunk/eventgen/issues/269.
> fixed bug #269

- splunk_eventgen/eventgen_api_server/eventgen_server_api.py
We explicitly exclude this stanza from our stanza count when calculating perDayVolume, but we assign the setting the stanza anyways. This results in an inaccurate total perDayVolume when we append the values of each stanza.
My fix will prevent us from assigning the setting to the stanza to mirror how we count each stanza.
> [global] perDayVolume

- splunk_eventgen/lib/eventgentimer.py
This pr is to address two things:
1. when using `seqfile` in token replacement with `KeyError` in #286 ;
2. OOM issue in #285 ;
Tested with `m5.4xlarge` (16 Cores, 64GB memory) more than 7 hours no OOM error.
> Fix bug 285

- splunk_eventgen/eventgen_api_server/eventgen_server_api.py
- splunk_eventgen/eventgen_core.py
- splunk_eventgen/lib/eventgenoutput.py
- splunk_eventgen/lib/eventgentimer.py
Previously, when using `multiprocess` mode with 20 `generatorWorkers`, the process will be killed as `Out of memory` error.
After adopting `pool` with `maxtasksperchild`, the processes are now down for OOM after more than 24 hours. 
Data ingestion with `perdayvolume=600`:
Process status and memory usage:
> Using multiprocess pool to address the OOM issue

- splunk_eventgen/eventgen_core.py
Bug found after hitting start endpoint on eg controller. All eg servers cannot retrieve status and produce the following log message:
`{"event": "'JoinableQueue' object has no attribute 'unfinished_tasks'", "level": "error", "timestamp": "2019-10-07T21:45:57.906983Z"}`
After change, eg server is able to retrieve status and still ends execution properly.
> Remove workerQueue unfinished tasks

- splunk_eventgen/eventgen_api_server/eventgen_controller.py
- splunk_eventgen/eventgen_api_server/eventgen_controller_api.py
- splunk_eventgen/eventgen_api_server/eventgen_server_api.py
Adding a healthcheck endpoint to determine controller and server connections to Redis
The controller will periodically (every 30 minutes) hit the endpoint and evaluate the connection statuses.
> Add Healthcheck Endpoint to Eventgen

- splunk_eventgen/eventgen_api_server/eventgen_controller.py
- splunk_eventgen/eventgen_api_server/eventgen_controller_api.py
- splunk_eventgen/eventgen_api_server/eventgen_server_api.py
Previous Healthcheck PR only coordinates servers to hit Redis. First we also want controller to hit redis as well.
> Make Controller also Ping Redis for Healthcheck

- splunk_eventgen/eventgen_api_server/eventgen_core_object.py
- splunk_eventgen/eventgen_api_server/eventgen_server.py
- splunk_eventgen/eventgen_api_server/eventgen_server_api.py
- Instead of copying bundle sample files into a default eventgen sample directory, this PR will create a new directory and move the sample files. This change is needed because [.*] stanza will try to work with every sample file if we use a default eventgen sample directory.
> Fixing api server

- splunk_eventgen/eventgen_api_server/eventgen_server_api.py
standalone healthcheck should not check for redis connection.
> Fixed standalone healthcheck

- Makefile
- dockerfiles/Dockerfile
After a bunch of testing on the OOM issue. I found this is caused by the `ujson` package which is needed by `conduct2` for perf testing. In this pr, I removed the installation step for `ujson` via git source code and I kicked two round of tests(one standalone and one triggered by perf test case) based on the new built docker image and the OOM issue is gone now.
> Fix oom caused by ujson

- splunk_eventgen/eventgen_api_server/eventgen_core_object.py
- splunk_eventgen/eventgen_api_server/eventgen_server_api.py
- splunk_eventgen/eventgen_core.py
- splunk_eventgen/lib/eventgenoutput.py
- splunk_eventgen/lib/eventgentimer.py
- splunk_eventgen/lib/plugins/output/syslogout.py
Fix existing issues:
1. Invoke `start/stop` multiple times will cause process leak since `multiprocessing.manager` process is not properly destroyed;
2. Broken pipe/EOFError exception will throw when calling the REST interface;
3. `/stop` endpoint will return 500 with `No file descriptor available`;
> Fix process leak and start/stop 500 issue

- splunk_eventgen/lib/eventgentoken.py
Thanks @Yangxulight finding this issue.
Using `random. SystemRandom` will cause high system call issue as stated here: #342
> Fix high system load issue

- requirements.txt
Coverage 5.0 is released December 4th but with bug: https://github.com/nedbat/coveragepy/issues/886
Fix the version to 4.5.4 in `requirements.txt`.
> Revert coverage version to 4.5.4

- docs/REFERENCE.md
- requirements.txt
- splunk_eventgen/lib/logging_config/__init__.py
I have done a few things here in this PR: 
1. Fix the test cases failure caused by new jinja version; (found when preparing the KT session)
2. Remove the config to print log to console as it will regarded as ERROR by Splunk; [Splunk Answers](https://answers.splunk.com/answers/792795/splunk-eventgen-652-folder-structure.html#answer-793817)
3. Change the logging level to ERROR by default;
4. Add `syslog` output plugin extra configuration by Splunk;
> Fix test case failure cased by new jinja version and update the log config

- docs/CONFIGURE.md
- docs/REFERENCE.md
- splunk_eventgen/splunk_app/README/eventgen.conf.spec
In PR #127 support for negative floats was introduced, as a fix for issue #126 .
Documentation added in that PR is not present anymore, this PR brings all docs up to date.
In the docs the mention that floats must be greater than 0 is removed.
Functionality is still present: 
- test exists: https://github.com/splunk/eventgen/blob/develop/tests/large/test_token_replacement.py#L56
- main regex: https://github.com/splunk/eventgen/blob/develop/splunk_eventgen/lib/eventgentoken.py#L179
> Add missing documentation for negative floats, as introduced in PR#127

- splunk_eventgen/eventgen_api_server/eventgen_server_api.py
This PR fix issue https://github.com/splunk/eventgen/issues/356. 
In summary, in controller server mode, the hosts will be used directly instead of using the FQDN.
> leave the httpevent outputServers as it is

- docs/SETUP.md
- docs/UPGRADE.md
- docs/index.md
when upgrading SA-eventgen from 6.x to 7.x, the modinput is broken. Because splunk app upgrade does not support to delete files in app folder. 
I created a doc to describe this issue and let user manually reinstall SA-eventgen 7.
> add upgrade guide in docs

- docs/CONFIGURE.md
- docs/REFERENCE.md
- splunk_eventgen/default/eventgen.conf
- splunk_eventgen/lib/eventgen_defaults
- splunk_eventgen/lib/eventgenconfig.py
- splunk_eventgen/splunk_app/README/eventgen.conf.spec
- tests/large/conf/eventgen_output_modinput.conf
For #394 
Changes the default source behavior to use the sample file name. Specifying a source in eventgen.conf still has the same behavior, and will prevent this.
> default source
